version: '2.1'
services:
  queue:
    build: 
      context: .
      dockerfile: ./Dockerfile
    tty: true
    networks:
      test_network:
        ipv6_address: fd00:420::3

networks:
  test_network:
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: fd00:420::/64
          gateway: fd00:420::1