---
version: 2
plan:
  project-key: SER
  name: MessageQueue
  key: MESS

stages:
  - Get dependencies:
    jobs:
      - Install checker dependencies with pip
  - Test:
      jobs:
        - Run smoke tests
        - Run exploit tests

Install checker dependencies with pip:
  tasks:
    - script:
        - pip3 install -r checker/requirements.txt

Run smoke tests:
  tasks:
    - script:
        - make test-smoke

Run exploit tests:
  tasks:
    - script:
        - make test-exploit
