---
version: 2
plan:
  project-key: SER
  name: MessageQueue
  key: MESS

stages:
  - First Build Stage:
      jobs:
        - Install dependencies
        - Build checker
        - Build service
        # - Run tests

Install dependencies:
  tasks:
    - script:
        - pip3 install -r checker/requirements.txt

Build checker:
  tasks:
    - script:
        - cd checker && docker-compose build

Build service:
  tasks:
    - script:
        - make su

# Run tests:
#   tasks:
#     - script:
#         - make test-smoke
#         - make test-exploit
