---
version: 2
plan:
  project-key: SER
  name: MessageQueue
  key: MESS

stages:
  - Install Dependencies Stage:
    jobs:
      - Install Checker Dependencies With pip
  - Test Stage:
      jobs:
        - Run Smoke Tests
        - Run Exploit Tests

Install Checker Dependencies With pip:
  tasks:
    - pip3 install -r checker/requirements.txt

Run Smoke Tests:
  tasks:
    - script:
        - make test-smoke

Run Exploit Tests:
  tasks:
    - script:
        - make test-exploit
