---
version: 2
plan:
  project-key: SER
  name: MessageQueue
  key: MESS

stages:
  - First Build Stage:
      jobs:
        - Install dependencies
        - Run tests

Install dependencies:
  tasks:
    - script:
        - pip3 install -r checker/requirements.txt

Run tests:
  tasks:
    - script:
        - make test-smoke
        - make test-exploit
