#! /bin/sh -

address="[fd00:1337:eeee:ba17::1]:8080"

case $1 in
	"")
		cat <<EOF
Usage:
./client a [-] topic
./client p topic message
./client r topic
./client s topic
./client t
EOF
		;;
	a*)
		shift
		printf '%s\n' "$*" | http patch "$address/add_topic"
		;;
	p*)
		shift
		topic="$1"
		printf '%s:%s\n' "$topic" "$*" | http post "$address/publish"
		;;
	r*)
		shift
		printf 'REPLAY:%s\n' "$*" | websocat "ws://$address/subscribe"
		;;
	s*)
		shift
		printf 'SUBSCRIBE: %s\n' "$*" | websocat "ws://$address/subscribe"
		;;
	t*)
		shift
		http "$address/topics"
		;;
	*)
		printf 'ERROR: unknown command: %s\n' "$*" >&2
		exit 1
		;;
esac

# vim: noexpandtab shiftwidth=8 softtabstop=8 tabstop=8
