version: '3.6'
services:
  backend:
    build: .
    environment:
    - MONGO_ENABLED=1
    - MONGO_HOST=deaddrop-checker_db
    - MONGO_PORT=27017
    - MONGO_USER=ipv6islove
    - MONGO_PASSWORD=dockerislove
    image: dockerreg.enowars.com:5000/deaddrop-checker-backend
    networks:
    - bridge
    - enoverlay
  frontend:
    depends_on:
    - backend
    deploy:
      labels:
      - traefik.enable=true
      - traefik.backend=deaddrop-checker_backend
      - traefik.docker.network=enoverlay
      - traefik.frontend.rule=Host:deaddrop.checker.enowars.com,service16.checker.enowars.com
      - traefik.port=80
      replicas: 1
    image: nginx:1.13-alpine
    networks:
    - enoverlay
    configs:
      - source: nginx_config
        target: /etc/nginx/conf.d/default.conf

  db:
    image: mongo
    networks:
      - enoverlay
    volumes:
      - deaddrop_db:/data/db
    deploy:
      replicas: 1
      #we need to fix the node otherwise the volumes are lost after migration :/
      placement:
        constraints:
          - "node.hostname==blade5"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ipv6islove
      MONGO_INITDB_ROOT_PASSWORD: dockerislove


networks:
  bridge:
    external: true
  enoverlay:
    external: true

volumes:
  deaddrop_db:

configs:
  nginx_config:
    file: ./nginx.conf