version: '2.3'
services:
  checker:
    build: .
  checker-nginx:
    image: nginx:1.13-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - checker
    ports:
      - 8080:80
