version: '3'
services:
  backend:
    image: 10.13.37.7:5000/deaddrop-checker-backend
    build: .
    networks:
      - bridge
      - enoverlay
    environment:
      - MONGO_ENABLED=1
      - MONGO_HOST=checkerdb_mongo_1
      - MONGO_PORT=27017
      - MONGO_USER=ipv6islove
      - MONGO_PASSWORD=dockerislove
  frontend:
    image: nginx:1.13-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - enoverlay
    labels:
      - "traefik.enable=true"
      - "traefik.backend=deaddrop-checker_backend"
      - "traefik.docker.network=enoverlay"
      - "traefik.frontend.rule=Host:deaddrop.checker.enowars.com,service16.checker.enowars.com"
      - "traefik.port=80"
networks:
  bridge:
    external: true
  enoverlay:
    external: true