version: '2.1'
services:
  mqchecker:
    build: .
    networks:
      checkernet:
        ipv6_address: fd00:1337:0:cecc:5::2
  checker-nginx:
    image: nginx:1.13-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - checker
    ports:
      - 8080:80
    networks:
      checkernet:
        ipv6_address: fd00:1337:0:cecc:5::1

networks:
  checkernet:
    external: true